name: STCREATIVE-TV Auto Update

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight
  workflow_dispatch:      # Manual trigger button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Run Script & Generate Data
        run: |
          chmod +x tvfzf.sh
          # Run the script in export mode
          ./tvfzf.sh --export > live_channels.m3u8
          echo "Last Updated: $(date)" > last_update.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add live_channels.m3u8 last_update.txt
          git commit -m "Automated update: New channel list generated" || echo "No changes to commit"
          git push
          
